DROP TABLE IF EXISTS musicians CASCADE;
DROP TABLE IF EXISTS songs;

CREATE TABLE musicians (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    country TEXT NOT NULL,
    age BIGINT NOT NULL
);

CREATE TABLE songs (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    genre TEXT NOT NULL,
    musician_id BIGINT REFERENCES musicians(id)
);